### ISSUE TITLE
Lack of 2 file--settings.cmake and Run failed

### ISSUE THREAD

**Issue by CarlCao17** [manu88/SeL4_101#1]
Hello, I am learning seL4 and try to run your seL4 project , but could not success.  I'm sure that I have do every steps you  said. I will explain the problem I have met. 
First, I found that there is a statement (cmake -DCMAKE_TOOLCHAIN_FILE="$SCRIPT_PATH"/kernel/gcc.cmake -G Ninja "$@" \
        -DSEL4_CACHE_DIR="$CACHE_DIR" -C ../settings.cmake "$SCRIPT_PATH"
) in init-build.sh, but there isn't a file-setting.cmake in the ${SCRIPT_PATH}—the top dir. 
Second, as you know, in default-CMakeList.txt , there also includes a settings.cmake file. But I could not find the file in CMAKE_MODULE_PATH or the CMake module path.
![problem_snap](https://user-images.githubusercontent.com/50823192/76636027-4a4e7b80-6583-11ea-9313-416c5e80dbef.png)

Third, I want to show you the picture. The program would stay in the state like the picture. And I  inserted many message statement and find out the program  stop in kernel/CMakeLists.txt (Row 54) like problem_snap2.png
![proble_snap2](https://user-images.githubusercontent.com/50823192/76635216-11fa6d80-6582-11ea-9d3b-f08754072e22.png)

**Comment by dinukaamarasinghe817** [comment]
> Hello, I am learning seL4 and try to run your seL4 project , but could not success. I'm sure that I have do every steps you said. I will explain the problem I have met. First, I found that there is a statement (cmake -DCMAKE_TOOLCHAIN_FILE="$SCRIPT_PATH"/kernel/gcc.cmake -G Ninja "$@" -DSEL4_CACHE_DIR="$CACHE_DIR" -C ../settings.cmake "$SCRIPT_PATH" ) in init-build.sh, but there isn't a file-setting.cmake in the ${SCRIPT_PATH}—the top dir. Second, as you know, in default-CMakeList.txt , there also includes a settings.cmake file. But I could not find the file in CMAKE_MODULE_PATH or the CMake module path. ![problem_snap](https://user-images.githubusercontent.com/50823192/76636027-4a4e7b80-6583-11ea-9313-416c5e80dbef.png)
> 
> Third, I want to show you the picture. The program would stay in the state like the picture. And I inserted many message statement and find out the program stop in kernel/CMakeLists.txt (Row 54) like problem_snap2.png ![proble_snap2](https://user-images.githubusercontent.com/50823192/76635216-11fa6d80-6582-11ea-9d3b-f08754072e22.png)

How did you solved the problem of missing `settings.cmake`?
